version: '3'
services:
  database:
    ports:
      - "5433:5432"
    image: "postgres:12" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    volumes:
      - /var/lib/postgresql/data/ # persist data even if container shuts down
#volumes:
      ##  database-data: # named volumes can be managed easier using docker-compose